let Employee=new Map();
Employee.set("name", "Jaskirat");
Employee.set("age", 28);
Employee.set("department", "Intelligence Agent");
console.log(Employee);
console.log(Employee.get("name"));
Employee.delete("age");
console.log(Employee);
console.log(Employee.has("name"));
console.log(Employee.has("age"));
Employee.set("age", 25);
console.log(Employee);
Employee.clear();
console.log(Employee);
