let name = "Bhuvanesh";
let age = 21;
let course = "Java Full Stack Developer";
let place = "Gudlavalleru";
console.log("Student Information:");
console.log("--------------------");
console.log("Name: " + name);
console.log("Age: " + age);
console.log("Course: " + course);
console.log("Place: " + place);
console.log("Thank you for providing the student information!");